# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from iris.io.transport import grpc_service_pb2 as iris_dot_io_dot_transport_dot_grpc__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in iris/io/transport/grpc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IrisServiceStub(object):
    """Service definition for bidirectional streaming between client and Iris.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BidirectionalStream = channel.stream_stream(
                '/iris.io.IrisService/BidirectionalStream',
                request_serializer=iris_dot_io_dot_transport_dot_grpc__service__pb2.BidirectionalStreamRequest.SerializeToString,
                response_deserializer=iris_dot_io_dot_transport_dot_grpc__service__pb2.BidirectionalStreamResponse.FromString,
                _registered_method=True)


class IrisServiceServicer(object):
    """Service definition for bidirectional streaming between client and Iris.
    """

    def BidirectionalStream(self, request_iterator, context):
        """Bidirectional streaming RPC for real-time message exchange.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IrisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=iris_dot_io_dot_transport_dot_grpc__service__pb2.BidirectionalStreamRequest.FromString,
                    response_serializer=iris_dot_io_dot_transport_dot_grpc__service__pb2.BidirectionalStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iris.io.IrisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iris.io.IrisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IrisService(object):
    """Service definition for bidirectional streaming between client and Iris.
    """

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/iris.io.IrisService/BidirectionalStream',
            iris_dot_io_dot_transport_dot_grpc__service__pb2.BidirectionalStreamRequest.SerializeToString,
            iris_dot_io_dot_transport_dot_grpc__service__pb2.BidirectionalStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
