# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iris/io/transport/grpc_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "iris/io/transport/grpc_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$iris/io/transport/grpc_service.proto\x12\x07iris.io"\xa9\x02\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x13\n\x0bsource_role\x18\x04 \x01(\t\x12\x13\n\x0btarget_role\x18\x05 \x01(\t\x12\x11\n\tdirection\x18\x06 \x01(\t\x12\x10\n\x08msg_type\x18\x07 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\t \x01(\t\x12\r\n\x05state\x18\n \x01(\t\x12\x30\n\x08metadata\x18\x0b \x03(\x0b\x32\x1e.iris.io.Message.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"f\n\x0c\x43ommandInput\x12\x10\n\x08msg_type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x13\n\x0bsource_role\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t"y\n\rCommandOutput\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x10\n\x08msg_type\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t"e\n\x0b\x43lientFrame\x12#\n\x07message\x18\x01 \x01(\x0b\x32\x10.iris.io.MessageH\x00\x12(\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x15.iris.io.CommandInputH\x00\x42\x07\n\x05\x66rame"f\n\x0bServerFrame\x12#\n\x07message\x18\x01 \x01(\x0b\x32\x10.iris.io.MessageH\x00\x12)\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x16.iris.io.CommandOutputH\x00\x42\x07\n\x05\x66rame*\x88\x01\n\nPermission\x12\r\n\tSEND_CHAT\x10\x00\x12\x10\n\x0cRECEIVE_CHAT\x10\x01\x12\x10\n\x0cSEND_COMMAND\x10\x02\x12\x13\n\x0fRECEIVE_COMMAND\x10\x03\x12\x0f\n\x0bRECEIVE_LOG\x10\x04\x12\r\n\tINTERRUPT\x10\x05\x12\x12\n\x0e\x45XECUTE_ACTION\x10\x06\x32T\n\x0bIrisService\x12\x45\n\x13\x42idirectionalStream\x12\x14.iris.io.ClientFrame\x1a\x14.iris.io.ServerFrame(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "iris.io.transport.grpc_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MESSAGE_METADATAENTRY"]._loaded_options = None
    _globals["_MESSAGE_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_PERMISSION"]._serialized_start = 784
    _globals["_PERMISSION"]._serialized_end = 920
    _globals["_MESSAGE"]._serialized_start = 50
    _globals["_MESSAGE"]._serialized_end = 347
    _globals["_MESSAGE_METADATAENTRY"]._serialized_start = 300
    _globals["_MESSAGE_METADATAENTRY"]._serialized_end = 347
    _globals["_COMMANDINPUT"]._serialized_start = 349
    _globals["_COMMANDINPUT"]._serialized_end = 451
    _globals["_COMMANDOUTPUT"]._serialized_start = 453
    _globals["_COMMANDOUTPUT"]._serialized_end = 574
    _globals["_CLIENTFRAME"]._serialized_start = 576
    _globals["_CLIENTFRAME"]._serialized_end = 677
    _globals["_SERVERFRAME"]._serialized_start = 679
    _globals["_SERVERFRAME"]._serialized_end = 781
    _globals["_IRISSERVICE"]._serialized_start = 922
    _globals["_IRISSERVICE"]._serialized_end = 1006
# @@protoc_insertion_point(module_scope)
