from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from iris.memory.models import ContentBlock
from iris.memory.sensory.readiness import ReadinessEvaluator


class SensoryMemoryProtocol(Protocol):
    def set_flush_callback(self, callback: Callable[[str, list[ContentBlock]], None]) -> None: ...
    def set_readiness_evaluator(self, evaluator: ReadinessEvaluator) -> None: ...
    def add_fragment(self, content: str, is_final: bool) -> None: ...
    def add_fragment_block(self, block: ContentBlock, is_final: bool) -> None: ...
    def flush(self) -> None: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
    def store_raw(self, content: str, room_id: str = "") -> None: ...
    def store_raw_block(self, block: ContentBlock, room_id: str = "") -> None: ...
    def retrieve(self) -> dict[str, Any]: ...

    @property
    def has_pending_raw(self) -> bool: ...

    @property
    def fragment_count(self) -> int: ...

    @property
    def accumulated_blocks(self) -> list[ContentBlock]: ...
