from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from iris.memory.models import ContentBlock
from iris.memory.sensory.models import PendingInputEntry, PendingInputKey, RawInput, SensorySnapshot
from iris.memory.sensory.readiness import ReadinessEvaluator


class SensoryMemoryProtocol(Protocol):
    def set_flush_callback(self, callback: Callable[[str, list[ContentBlock]], None]) -> None: ...
    def set_readiness_evaluator(self, evaluator: ReadinessEvaluator) -> None: ...
    def add_fragment(self, content: str, is_final: bool, room_id: str = "") -> None: ...
    def add_fragment_block(self, block: ContentBlock, is_final: bool, room_id: str = "") -> None: ...
    def flush(self, room_id: str = "") -> None: ...
    def clear(self, room_id: str | None = None) -> None: ...
    def clear_raw(self, room_id: str | None = None) -> None: ...
    def close(self) -> None: ...
    def store_raw(self, content: str, room_id: str = "", account_id: str = "", session_id: str = "") -> None: ...
    def store_raw_block(
        self, block: ContentBlock, room_id: str = "", account_id: str = "", session_id: str = ""
    ) -> None: ...
    def retrieve(self, room_id: str = "") -> SensorySnapshot: ...
    def take_raw(self, room_id: str = "") -> RawInput | None: ...

    def add_pending_input(self, account_id: str, room_id: str, content: str) -> None: ...
    def take_pending_input(self) -> dict[PendingInputKey, list[PendingInputEntry]]: ...
    def clear_pending_input(self) -> None: ...
    def flush_pending(self) -> dict[PendingInputKey, list[PendingInputEntry]]: ...
    def store_and_flush_pending_block(self, block: ContentBlock, account_id: str, room_id: str = "") -> None: ...

    def has_pending_raw(self, room_id: str = "") -> bool: ...

    @property
    def has_pending_input(self) -> bool: ...

    @property
    def pending_input(self) -> dict[PendingInputKey, list[PendingInputEntry]]: ...

    @property
    def pending_lock(self) -> Any: ...

    def fragment_count(self, room_id: str = "") -> int: ...

    def accumulated_blocks(self, room_id: str = "") -> list[ContentBlock]: ...

    def get_active_room_ids(self) -> list[str]: ...
