from __future__ import annotations

from typing import Protocol

from iris.memory.models import ContentBlock
from iris.memory.short_term.models import MAX_CONTEXT_CHARS, ActiveUser, ShortTermSearchResult, ShortTermTurn


class ShortTermMemoryProtocol(Protocol):
    def add_turn(self, role: str, blocks: list[ContentBlock], account_id: str = "", room_id: str = "") -> None: ...
    def search(
        self, query: str, max_results: int = 5, room_id: str = "", account_id: str = ""
    ) -> list[ShortTermSearchResult]: ...
    def search_entities(self, entity_name: str) -> list[ShortTermTurn]: ...
    def render_context(
        self, max_chars: int = MAX_CONTEXT_CHARS, query: str | None = None, room_id: str = "", account_id: str = ""
    ) -> str: ...
    def get_recent_turns(self, n: int = 4, room_id: str = "", account_id: str = "") -> list[ShortTermTurn]: ...
    def get_unconsolidated_turns(self, room_id: str = "", account_id: str = "") -> list[ShortTermTurn]: ...
    def mark_consolidated(self, room_id: str = "", account_id: str = "") -> None: ...
    def clear(self) -> None: ...
    def should_consolidate(self, room_id: str = "", account_id: str = "") -> bool: ...
    def add_user(self, account_id: str, display_name: str, room_id: str = "") -> None: ...
    def remove_user(self, account_id: str, room_id: str = "") -> None: ...
    def get_active_users(self) -> list[ActiveUser]: ...
    def get_users_by_room(self, room_id: str) -> list[ActiveUser]: ...

    @property
    def current_topics(self) -> list[str]: ...

    @property
    def turn_count(self) -> int: ...
