from __future__ import annotations

from typing import Protocol

from iris.memory.models import ContentBlock
from iris.memory.short_term.models import MAX_CONTEXT_CHARS, SearchResult, TurnData


class ShortTermMemoryProtocol(Protocol):
    def add_turn(self, role: str, blocks: list[ContentBlock], account_id: str = "", room_id: str = "") -> None: ...
    def search(
        self, query: str, max_results: int = 5, room_id: str = "", account_id: str = ""
    ) -> list[SearchResult]: ...
    def search_entities(self, entity_name: str) -> list[TurnData]: ...
    def render_context(
        self, max_chars: int = MAX_CONTEXT_CHARS, query: str | None = None, room_id: str = "", account_id: str = ""
    ) -> str: ...
    def get_recent_turns(self, n: int = 4, room_id: str = "", account_id: str = "") -> list[TurnData]: ...
    def get_unconsolidated_turns(self, room_id: str = "", account_id: str = "") -> list[TurnData]: ...
    def mark_consolidated(self, up_to_index: int | None = None) -> None: ...
    def clear(self) -> None: ...
    def should_consolidate(self) -> bool: ...
    def add_user(self, account_id: str, display_name: str, room_id: str = "") -> None: ...
    def remove_user(self, account_id: str, room_id: str = "") -> None: ...
    def get_active_users(self) -> list[tuple[str, str]]: ...
    def get_users_by_room(self, room_id: str) -> list[tuple[str, str]]: ...

    @property
    def current_topics(self) -> list[str]: ...

    @property
    def turn_count(self) -> int: ...
